apiVersion: v1
kind: ConfigMap
metadata:
  name: html-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>CONFIGMAP</title>
    </head>
    <body>
        <h1>Hello from ConfigMap!</h1>
    </body>
    </html>
